### ISSUE TITLE
YAML reader inclusion?

### ISSUE THREAD

**Issue by luisarmona** [gslab-econ/gslab_stata#7]
Hey @arosenbe ,
 I am not sure who is in charge of this repo but I wanted to share some code for STATA. I wrote a short .ado file to parse yaml file as we use them to define constants at the top of repositories (Typically in a constants.yaml type file) and write these to globals/locals. My file is located [here](https://github.com/gslab-econ/newsworthy/blob/development/source/lib/readyaml.ado). The original hope was sharing this code would help gslab use yaml files for STATA still. 

unfortunately, I just noticed via a reference [here](https://github.com/gslab-econ/ad-price-drivers/blob/master/source/analysis/tv-ad-price/superbowl.do) that apparently a STATA YAML reader already exists, but was unable to locate it in gslab_stata or generic googling. So I thought I would open this issue to complete one of the following: 

- input the referenced yaml program in the ad-price-driver STATA script as a part of gslab_stata so all gslab people have it.
- include my program so that everyone has a YAML parser 
- include some other YAML reader I am unaware of as part of gslab_stata

I am going to go out on a limb and assume the referenced yaml reader in the ad-price-driver script is far more sophisticated than mine, and probably should be the standard one used.

Let me know your thoughts

**Comment by arosenbe** [comment]
@luisarmona, the referenced yaml parser is [here](https://github.com/gslab-econ/stata-misc). Someone else already had it on GH, so we figured it'd be more appropriate to fork their repo (for stability) than to move all their scripts into this repo. 

We'd be happy to upgrade if you think your parser is better than the one we're currently using. We just went with the publicly available one because we didn't want to write something ourselves. 

I definitely get that this split-storage is confusing and not intuitive. If we decide not to upgrade (I'll wait on you for this) then I'll add some text top the readme mentioning this forked yaml parser.

**Comment by luisarmona** [comment]
Yeah I think it would make most sense to go with the public fork (as I mentioned I am very confident it their parser is better than mine). The bigger concern was the confusion of this parser seemingly not existing, and so I spent some time building something duplicitous. I think the best solution would be to  include stata_misc in the build sheet, so that by default gslab members have access to this (and add a note in the readme that you suggested). I am happy to help with this work.

**Comment by arosenbe** [comment]
I'm really sorry about the time you spent building something that already exists. That's not good.

I do think the root of the issue my poor job of on-boarding you, rather than poor documentation. Let me address that. All lab projects now use the [template](https://github.com/gslab-econ/template) which has a self-contained and publicly available set of dependencies—the current head of template links to the yaml parser, and the nearly-finished dev branch (4.1.0)  has a script that will install it for you. This represents our desire to make some super cool 🌈 lab resources accessible to people who aren't members, and you should look to template for the most recent dependencies.  

The (gated) build sheet wasn't updated. That's an oversight on our part, and I'll go update that now. In the future, think of the build sheet as a lab-only resource to help meet the template's dependencies in a variety of environments, not as a guarantee that running it will bring your environment into concordance with any specific repository's dependencies.

**Comment by luisarmona** [comment]
Thanks for updating!
 Yeah it appears I was unfamiliar with the template repo, and so for this reason did not download the STATA yaml parser  . It seems like simply cloning and running the template would be a good practice task for the future? something to think about as its a little more involved than the practice task currently assigned to new RAs and still hits all the aspects of GSLAB we want people to be familiar with.

**Comment by luisarmona** [comment]
Given the successful PR, I will close this issue. See  (issue 134 in admin)[https://github.com/gslab-econ/admin/issues/134] for further information about this issue

**Comment by arosenbe** [comment]
Yeah, I'm really sorry about that. Cloning and running the template definitely should be included in the practice task. I'll document this somewhere. 

I would actually go a step farther about the template though. It's not just aspects of GSLab, it's the basic building block for every repository we make. Any new repo should start by copying over the structure that's in the template.
